#!/usr/bin/env bash
# phase3-setup-pilot.sh
# One-time setup: create the isolated ejbca_pilot MariaDB database and write
# pilot credentials.  Does NOT touch the production ejbca database.
# Safe to re-run (idempotent).
#
# Usage:
#   ./phase3/phase3-setup-pilot.sh
#
# Env overrides (optional):
#   PILOT_DB_NAME     — pilot database name (default: ejbca_pilot)
#   PILOT_DB_USER     — pilot database user (default: ejbca_pilot)
#   PILOT_DB_PASSWORD — password; auto-generated if not set and no existing creds file
#
# After this script:
#   ./phase3/phase3-run-wildfly30-pilot.sh   — start EJBCA on pilot database

set -euo pipefail

ROOT="${HOME}/rootCA"
PHASE3_DIR="$ROOT/phase3"
PILOT_CREDS_FILE="$PHASE3_DIR/.pilot-db-credentials"

PILOT_DB_NAME="${PILOT_DB_NAME:-ejbca_pilot}"
PILOT_DB_USER="${PILOT_DB_USER:-ejbca_pilot}"

# --- Resolve password -------------------------------------------------------
if [[ -z "${PILOT_DB_PASSWORD:-}" ]]; then
  if [[ -f "$PILOT_CREDS_FILE" ]]; then
    echo "[setup-pilot] Sourcing existing pilot credentials from $PILOT_CREDS_FILE"
    # shellcheck source=/dev/null
    source "$PILOT_CREDS_FILE"
  else
    PILOT_DB_PASSWORD="$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)"
    echo "[setup-pilot] Generated new pilot database password"
  fi
fi

# --- Verify MariaDB is reachable (root admin path via sudo) -----------------
echo "[setup-pilot] Verifying MariaDB is running"
if ! sudo mysql -e "SELECT 1" >/dev/null 2>&1; then
  echo "ERROR: Cannot connect to MariaDB via sudo — ensure MariaDB is running"
  echo "       Start MariaDB:  sudo systemctl start mariadb"
  exit 1
fi

# --- Create pilot database and user -----------------------------------------
echo "[setup-pilot] Creating pilot database '${PILOT_DB_NAME}' and user '${PILOT_DB_USER}'"
sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${PILOT_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${PILOT_DB_USER}'@'localhost'
  IDENTIFIED BY '${PILOT_DB_PASSWORD}';
ALTER USER '${PILOT_DB_USER}'@'localhost'
  IDENTIFIED BY '${PILOT_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${PILOT_DB_NAME}\`.* TO '${PILOT_DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

echo "[setup-pilot] Verifying pilot database connection"
if ! mysql -u"${PILOT_DB_USER}" -p"${PILOT_DB_PASSWORD}" "${PILOT_DB_NAME}" -e "SELECT 1" >/dev/null 2>&1; then
  echo "ERROR: Cannot connect to MariaDB as ${PILOT_DB_USER}@localhost — check credentials"
  exit 1
fi
echo "[setup-pilot] Connection verified"

# --- Write pilot credentials file -------------------------------------------
echo "[setup-pilot] Writing pilot credentials file: $PILOT_CREDS_FILE"
mkdir -p "$PHASE3_DIR"
cat > "$PILOT_CREDS_FILE" <<EOF
# EJBCA Pilot MariaDB credentials
# Generated by phase3-setup-pilot.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Sourced by phase3-run-wildfly30-pilot.sh — keep this file protected (mode 600).
EJBCA_DB_NAME=${PILOT_DB_NAME}
EJBCA_DB_USER=${PILOT_DB_USER}
EJBCA_DB_PASSWORD=${PILOT_DB_PASSWORD}
EOF
chmod 600 "$PILOT_CREDS_FILE"

# --- Confirm isolation from production --------------------------------------
echo "[setup-pilot] Confirming production database is untouched"
PROD_CREDS="$ROOT/phase1/.db-credentials"
if [[ -f "$PROD_CREDS" ]]; then
  # shellcheck source=/dev/null
  source "$PROD_CREDS"
  PROD_TABLE_COUNT="$(mysql -u"${EJBCA_DB_USER}" -p"${EJBCA_DB_PASSWORD}" "${EJBCA_DB_NAME}" \
    -sNe "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${EJBCA_DB_NAME}';" 2>/dev/null || echo '?')"
  echo "[setup-pilot] Production database '${EJBCA_DB_NAME}' has ${PROD_TABLE_COUNT} tables — unchanged"
fi

# --- Done -------------------------------------------------------------------
echo ""
echo "[setup-pilot] Pilot setup complete."
echo "  Pilot DB   : ${PILOT_DB_NAME}"
echo "  Pilot user : ${PILOT_DB_USER}"
echo "  Creds file : $PILOT_CREDS_FILE (mode 600)"
echo ""
echo "Next steps:"
echo "  1. Start EJBCA on the pilot database:"
echo "       ./phase3/phase3-run-wildfly30-pilot.sh"
echo "  2. Log in to EJBCA admin web to verify pilot profiles are present:"
echo "       http://127.0.0.1:8080/ejbca/adminweb/"
echo "  3. Issue pilot root CA using RootCAPilot-ECC384-SHA384 profile."
echo "  4. When pilot testing is complete, restore production context:"
echo "       ./phase3/phase3-run-wildfly30-prod.sh"
