#!/usr/bin/env bash
# phase1-setup-mariadb.sh
# One-time setup: install MariaDB, create EJBCA database, install WildFly JDBC module,
# and write runtime credentials.  Safe to re-run (idempotent).
#
# Usage:
#   ./phase1/phase1-setup-mariadb.sh
#
# Env overrides (optional):
#   EJBCA_DB_NAME     — database name (default: ejbca)
#   EJBCA_DB_USER     — database user (default: ejbca)
#   EJBCA_DB_PASSWORD — password; auto-generated if not set and no existing creds file
#
# After this script completes:
#   1. Rebuild EJBCA:  ./phase1/phase1-build-ejbca9.sh
#   2. Start runtime:  ./phase1/phase1-run-wildfly30-ejbca9.sh

set -euo pipefail

ROOT="${HOME}/rootCA"
PHASE1_DIR="$ROOT/phase1"
WILDFLY_HOME="$ROOT/artifacts/appserver/wildfly-30.0.1.Final"
EJBCA_CONF_DIR="$ROOT/artifacts/ejbca/ejbca-ce-r9.3.7/conf"
DB_CREDS_FILE="$PHASE1_DIR/.db-credentials"

EJBCA_DB_NAME="${EJBCA_DB_NAME:-ejbca}"
EJBCA_DB_USER="${EJBCA_DB_USER:-ejbca}"

# --- Resolve password -------------------------------------------------------
if [[ -z "${EJBCA_DB_PASSWORD:-}" ]]; then
  if [[ -f "$DB_CREDS_FILE" ]]; then
    echo "[setup-mariadb] Sourcing existing credentials from $DB_CREDS_FILE"
    # shellcheck source=/dev/null
    source "$DB_CREDS_FILE"
  else
    EJBCA_DB_PASSWORD="$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)"
    echo "[setup-mariadb] Generated new database password"
  fi
fi

# --- Step 1: Install packages ------------------------------------------------
echo "[setup-mariadb] Step 1: Installing mariadb-server and mariadb-java-client"
sudo dnf -y install mariadb-server mariadb-java-client

# --- Step 2: Enable and start MariaDB ----------------------------------------
echo "[setup-mariadb] Step 2: Enabling and starting MariaDB service"
sudo systemctl enable mariadb
sudo systemctl start mariadb

# Brief wait for socket to be ready
for _ in 1 2 3 4 5; do
  if sudo mysql -e "SELECT 1" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

# --- Step 3: Create database and user ----------------------------------------
echo "[setup-mariadb] Step 3: Creating database '${EJBCA_DB_NAME}' and user '${EJBCA_DB_USER}'"
sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${EJBCA_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${EJBCA_DB_USER}'@'localhost'
  IDENTIFIED BY '${EJBCA_DB_PASSWORD}';
ALTER USER '${EJBCA_DB_USER}'@'localhost'
  IDENTIFIED BY '${EJBCA_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${EJBCA_DB_NAME}\`.* TO '${EJBCA_DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

echo "[setup-mariadb] Verifying database connection"
if ! mysql -u"${EJBCA_DB_USER}" -p"${EJBCA_DB_PASSWORD}" "${EJBCA_DB_NAME}" -e "SELECT 1" >/dev/null 2>&1; then
  echo "ERROR: Cannot connect to MariaDB as ${EJBCA_DB_USER}@localhost — check credentials or MariaDB status"
  exit 1
fi
echo "[setup-mariadb] Connection verified"

# --- Step 4: Install MariaDB JDBC driver as a WildFly module ----------------
echo "[setup-mariadb] Step 4: Installing MariaDB JDBC driver as WildFly module"

JDBC_JAR="$(find /usr/lib/java /usr/share/java -maxdepth 3 -name 'mariadb-java-client*.jar' ! -name '*.bak' 2>/dev/null | sort -V | tail -n 1)"
if [[ -z "$JDBC_JAR" ]]; then
  echo "ERROR: mariadb-java-client JAR not found under /usr/lib/java/ or /usr/share/java/"
  echo "       Ensure 'mariadb-java-client' RPM package is installed."
  exit 1
fi
echo "[setup-mariadb] Found JDBC JAR: $JDBC_JAR"

MARIADB_MODULE_DIR="$WILDFLY_HOME/modules/org/mariadb/jdbc/main"
mkdir -p "$MARIADB_MODULE_DIR"
cp -f "$JDBC_JAR" "$MARIADB_MODULE_DIR/mariadb-java-client.jar"

cat > "$MARIADB_MODULE_DIR/module.xml" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.3" name="org.mariadb.jdbc">
    <resources>
        <resource-root path="mariadb-java-client.jar"/>
    </resources>
    <dependencies>
        <module name="javax.api"/>
        <module name="javax.transaction.api"/>
    </dependencies>
</module>
EOF

echo "[setup-mariadb] WildFly module installed: $MARIADB_MODULE_DIR"

# --- Step 5: Write EJBCA database.properties ---------------------------------
echo "[setup-mariadb] Step 5: Writing EJBCA conf/database.properties"
mkdir -p "$EJBCA_CONF_DIR"
cat > "$EJBCA_CONF_DIR/database.properties" <<EOF
# EJBCA database configuration — MariaDB
# Generated by phase1-setup-mariadb.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
#
# NOTE: Runtime credentials are managed in WildFly via the credentials file
#       ($DB_CREDS_FILE).
#       The password is NOT stored in this file.
#       This file sets the build-time database dialect only.

datasource.jndi-name=EjbcaDS
database.name=mysql
EOF
chmod 640 "$EJBCA_CONF_DIR/database.properties"

# --- Step 6: Write runtime credentials file ----------------------------------
echo "[setup-mariadb] Step 6: Writing runtime credentials file"
cat > "$DB_CREDS_FILE" <<EOF
# EJBCA MariaDB runtime credentials
# Generated by phase1-setup-mariadb.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Sourced by phase1-run-wildfly30-ejbca9.sh — keep this file protected (mode 600).
EJBCA_DB_NAME=${EJBCA_DB_NAME}
EJBCA_DB_USER=${EJBCA_DB_USER}
EJBCA_DB_PASSWORD=${EJBCA_DB_PASSWORD}
EOF
chmod 600 "$DB_CREDS_FILE"

# --- Done --------------------------------------------------------------------
echo ""
echo "[setup-mariadb] Setup complete."
echo "  Database : ${EJBCA_DB_NAME}"
echo "  User     : ${EJBCA_DB_USER}"
echo "  Creds    : $DB_CREDS_FILE (mode 600)"
echo ""
echo "Next steps:"
echo "  1. Rebuild EJBCA EAR with MariaDB dialect:"
echo "       ./phase1/phase1-build-ejbca9.sh"
echo "  2. Start the EJBCA runtime:"
echo "       ./phase1/phase1-run-wildfly30-ejbca9.sh"
